### ISSUE TITLE
Deliverables/Task List

### ISSUE THREAD

**Issue by alexa-whitney** [alexa-whitney/makesite#1]
### Complete the below tasks _IN ORDER_

**v1.0 Requirements** (_Due by Wed 4/3/24_)

- [x]  Edit line 4 of README.md. Change this line to the following, replacing YOUR_USERNAME and YOUR_REPONAME with your GitHub username and repository name respectively.
- [x]  Read in the contents of the provided first-post.txt file.
- [x]  Edit the provided HTML template (template.tmpl) to display the contents of first-post.txt.
- [x]  Render the contents of first-post.txt using Go Templates and print it to stdout.
- [x]  Write the HTML template to the filesystem to a file. Name it first-post.html.
- [x]  Manually test the generated HTML page by running ./makesite. Double-click the first-post.html file that appears in your directory after running the command to open the generated page in your browser.
- [x]  Add, commit, and push to GitHub.
- [x]  Add a new flag to your command named file. This flag represents the name of any .txt file in the same directory as your program. Run ./makesite --file=latest-post.txt to test.
- [x]  Update the save function to use the input filename to generate a new HTML file. For example, if the input file is named latest-post.txt, the generated HTML file should be named latest-post.html.
- [x]  Add, commit, and push to GitHub.

**v1.0 Stretch Challenges**

- [x]  Use Bootstrap, or another CSS framework, to enhance the style and readability of your template. Get creative! Writing your very own website generator is a great opportunity to broadcast your style, personality, and development preferences to the world!

**v1.1 Requirements** (_Due by Mon 4/8/24_)

- [x] Create 3 new .txt files for testing in the same directory as your project.
- [x] Add a new flag to the makesite command named dir.
- [x] Use the flag to find all .txt files in the given directory. Print them to stdout.
- [x] With the list of .txt files you found, generate an HTML page for each.
- [x] Run ./makesite --dir=. to test in your local directory.
- [x] Add, commit, and push to GitHub.

**v1.1 Stretch Challenges**
- [x]  Recursively find all .txt files in the given directory, as well as it's subdirectories. Print them to stdout to make sure. Generate an HTML page for each.
- [x] When your program finishes, print: Success! Generated 5 pages. The Success! substring must be bold green, and the count (5) must be bold.
- [x] Modify the success message to read: Success! Generated 5 pages (18.2kB total). Calculate the total by summing the size of each HTML file, then converting the total to kilobytes. Always return one significant digit after the decimal point.
- [x] Determine how long it took to execute your static site generator. Modify the success message to read: Success! Generated 5 pages (18.2kB total) in 3.25 seconds. Always return two significant digits after the decimal point.
- [ ] Test your solutions to these stretch challenges on many different directories containing .txt files. Are there any ways to make your code faster?

**v1.2 Requirements** (_Due by Wed 4/10/24_)

- [x]  Initialize Go modules in your project.
- [x]  Add any third party library to your project to enhance it's functionality. Some ideas you might consider include **_(CHOOSE ONLY ONE)_**:
- [ ]  Translating page content using Google Translate.
- [ ]  Parse Markdown (.md) files and transform them into HTML. `#` through `######` should translate to `<h1>` through `<h6>` elements.
- [x]  **_FILL IN THE BLANK_**: I will use the __________________________________ library. The documentation is located at __________________________________. My goal is to use it to __________________________________.
- [x]  Add, commit, and push to GitHub.
